apiVersion: v1
data:
  config-file1.conf: |
    server {
        listen              80;
        listen              443 ssl;
        server_name         www.kubia-example.com;
        ssl_certificate     certs/https.cert;
        ssl_certificate_key certs/https.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

    }
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-20T09:06:25Z"
  name: my-config1
  namespace: default
 
